import Head from 'next/head'

import { CodeEditor } from '../components/editor/CodeEditor'
import { Result } from '../components/result/Result'
import ResultContextProvider from '../lib/context/ResultContext'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <ResultContextProvider>
          <CodeEditor />
          <Result />
        </ResultContextProvider>
      </main>
    </div>
  )
}
